version: '3.1'


# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./log_dir - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./buildserver_pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
  teamcity:
    image: jetbrains/teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - /Users/ivan.kravchenko/teamcity/datadir:/data/teamcity_server/datadir
      - /Users/ivan.kravchenko/teamcity/logs:/opt/teamcity/logs
    depends_on:
      - db
  teamcity-agent-1:
    image: jetbrains/teamcity-agent
    restart: always
    privileged: true
    volumes:
      - /Users/ivan.kravchenko/teamcity/data/teamcity_agent/conf:/data/teamcity_agent/conf
    environment:
      - AGENT_NAME="Agent 1"
      - SERVER_URL=teamcity:8111
      - DOCKER_IN_DOCKER=start